### ISSUE TITLE
Node rest API...

### ISSUE THREAD

**Issue by Snille** [RMHonor/sure-pet-care#2]
Hi! I'm very new to setting up a rest API from scratch... So this is a real nub question. :)

I want to setup a small node app that is just a "get status" and "set status" on the cats and the flaps.
But, being a nub, I don't really know how... :)
So, if you have an example on how to include your package in a script it would be great! :)

This is as far as I've come... 
```javascript
const express = require('express');
const app = express();
const client = ('sure-pet-care-client');

// How to authenticate and set / get status?... :)

// Route home
app.get('/', (req, res) => {
	res.send('Home');
});

// Route post
app.get('/post', (req, res) => {
	res.send('Post');
});

// Route get
app.get('/get', (req, res) => {
	res.send('Get');
});

// Port to listen on.
app.listen(3000);
```

**Comment by RMHonor** [comment]
You'll need to create a new instance of the client, and then login, something like the following:

```javascript
const express = require('express');
const app = express();
const { SurePetCareClient } = ('sure-pet-care-client');

// create new client
const client = new SurePetCareClient();

// authenticate the client
client.authenticate('username', 'password').then(() => {
  // Route home
  app.get('/', (req, res) => {
	res.send('Home');
  });

  // Route post
  app.get('/post', (req, res) => {
	res.send('Post');
  });

  // Route get
  app.get('/get', (req, res) => {
	res.send('Get');
  });

  // Port to listen on.
  app.listen(3000);
});
```

Unfortunately there's no way to get/set the status of the flap, just the cats themselves. I'll be sure to add this ASAP.

I'll add an example usage for both TypeScript/vanilla JS too.

**Comment by Snille** [comment]
Thank you for this! :) I'll start with a way to "get" the information first.
Examples would be really appreciated of course! :)
